"""Adapt pinned Eigen kernels to caller-owned work arrays; leave arithmetic unchanged."""
import sys
import re
from pathlib import Path


def replace(text, old, new):
    if old not in text:
        raise RuntimeError('Unexpected Eigen source: ' + old)
    return text.replace(old, new)


def function(text, signature):
    start = text.index(signature)
    begin = text.index('{', start)
    depth = 1
    end = begin + 1
    while depth:
        depth += (text[end] == '{') - (text[end] == '}')
        end += 1
    return text[start:end]


def main():
    eigen, output = map(Path, sys.argv[1:])
    amd = (eigen / 'Eigen/src/OrderingMethods/Amd.h').read_text()
    order = function(amd, 'void minimum_degree_ordering(')
    order = replace(order, 'void minimum_degree_ordering(SparseMatrix<Scalar,ColMajor,StorageIndex>& C, PermutationMatrix<Dynamic,Dynamic,StorageIndex>& perm)',
                    'inline void orderSparse(newton::SparseStorage& C, std::vector<int>& perm, std::vector<int>& workspace)')
    order = replace(order, '  using std::sqrt;', '  typedef int StorageIndex;\n  using std::sqrt;')
    order = replace(order, 'ei_declare_aligned_stack_constructed_variable(StorageIndex,W,8*(n+1),0);',
                    'workspace.resize(8*(n+1));\n  StorageIndex* W = workspace.data();')
    order = replace(order, 'perm.indices().data()', 'perm.data()')
    order = replace(order, 'perm.indices().conservativeResize(n);', 'perm.resize(n);')
    order = re.sub(r'\blast\b', 'previousNode', order)
    chol = (eigen / 'Eigen/src/SparseCholesky/SimplicialCholesky_impl.h').read_text()
    analyze = function(chol, 'void SimplicialCholeskyBase<Derived>::analyzePattern_preordered(')
    analyze = replace(analyze, 'SimplicialCholeskyBase<Derived>::analyzePattern_preordered', 'analyzePattern')
    analyze = replace(analyze, 'ei_declare_aligned_stack_constructed_variable(StorageIndex, tags, size, 0);',
                      'm_tags.resize(size);\n  StorageIndex* tags = m_tags.data();')
    analyze = replace(analyze, '  m_isInitialized     = true;\n  m_info              = Success;\n  m_analysisIsOk      = true;\n  m_factorizationIsOk = false;', '')
    factor = function(chol, 'void SimplicialCholeskyBase<Derived>::factorize_preordered(')
    factor = replace(factor, 'void SimplicialCholeskyBase<Derived>::factorize_preordered', 'bool factorize')
    factor = replace(factor, '  eigen_assert(m_analysisIsOk && "You must first call analyzePattern()");\n', '')
    factor = replace(factor, 'm_parent.size()==ap.rows()', 'Eigen::Index(m_parent.size())==ap.rows()')
    factor = replace(factor, 'm_nonZerosPerCol.size()==ap.rows()', 'Eigen::Index(m_nonZerosPerCol.size())==ap.rows()')
    for name, scalar in [('y', 'Scalar'), ('pattern', 'StorageIndex'), ('tags', 'StorageIndex')]:
        old = next(line.strip() for line in factor.splitlines() if 'ei_declare_aligned_stack_constructed_variable' in line and ', '+name+',' in line.replace('  ', ' '))
        factor = replace(factor, old, f'm_{name}.resize(size);\n  {scalar}* {name} = m_{name}.data();')
    factor = replace(factor, '  m_info = ok ? Success : NumericalIssue;\n  m_factorizationIsOk = true;', '  return ok;')
    license_amd = amd[:amd.index('#ifndef')]
    license_chol = chol[:chol.index('#ifndef')]
    header = '// Generated by PrepareStorageKernels.py from Eigen 3.4.0.\n// Changes are limited to interfaces and reusable storage.\n'
    header += license_amd + '\nnamespace Eigen { namespace internal {\n' + order + '\n}}\n'
    header += license_chol + '''
namespace newton
{
class StorageCholesky
{
    typedef SparseStorage CholMatrixType;
    typedef int StorageIndex;
    typedef Eigen::Index Index;
    typedef double Scalar;
    typedef double RealScalar;
public:
    SparseStorage m_matrix;
'''
    header += analyze + '\n\ttemplate<bool DoLDLT>\n' + factor.replace('  using std::sqrt;', '  using std::sqrt;\n  namespace numext = Eigen::numext;')
    header += '''
private:
    std::vector<int> m_parent, m_nonZerosPerCol, m_tags, m_pattern;
    std::vector<double> m_y, m_diag;
    const double m_shiftScale = 1.0, m_shiftOffset = 0.0;
};
}
'''
    output.write_text(header)


if __name__ == '__main__':
    main()
